-- DropForeignKey
ALTER TABLE `iptv` DROP FOREIGN KEY `IPTV_idDNS_fkey`;

-- AlterTable
ALTER TABLE `iptv` MODIFY `idDNS` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `IPTV` ADD CONSTRAINT `IPTV_idDNS_fkey` FOREIGN KEY (`idDNS`) REFERENCES `DNS_Stick`(`idDNS`) ON DELETE SET NULL ON UPDATE CASCADE;
